FROM docker.io/bitnami/kafka:3.4

EXPOSE 9092

VOLUME /data:/bitnami

COPY create-topics.sh /opt/bitnami/scripts/

ENV KAFKA_BROKER_ID=1
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
ENV KAFKA_CFG_ZOOKEEPER_CONNECT=host.docker.internal:2181
ENV ALLOW_PLAINTEXT_LISTENER=yes

CMD ["./opt/bitnami/scripts/create-topics.sh"]
